version: "3.8"
services:
  web:
    build:
      context: .
    ports:
      - "5000:5000"
    networks:
      - webnet
  reverse-proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
